
version: "3"
services:
  nginx:
    image: "jwilder/nginx-proxy:latest"
    restart: "always"
    build: ../lampy-nginx/
    container_name: global-nginx

    ports:
      - 80:80
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      net:
        external: true

   
networks:
  default:
      ipam:
        config:
        - subnet: 172.20.0.1/16
  lampy-docker_default:
    external: true
  lm-docker_default:
    external: true
  bc-proheadprodcom_default:
    external: true
