
version: "3"

services:

  nginx:
    build: ../lampy-nginx/
    container_name: global-nginx

    ports:
      - 80:80
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - lampy-docker_default
      - lm-docker_default

networks:
  default:
      ipam:
        config:
        - subnet: 172.18.0.1/16