
version: "3"
services:
  nginx:
    build: ./
    container_name: global-nginx
    ports:
      - 80:80
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - main-net
networks:
  main-net:
    external: true